parameters:

    #
    # Providers
    #
    elcodi.container_parameters.class: Symfony\Component\DependencyInjection\ParameterBag\ParameterBag
    elcodi.core.core.service.manager_provider.class: Elcodi\CoreBundle\Services\ManagerProvider
    elcodi.core.core.service.repository_provider.class: Elcodi\CoreBundle\Services\RepositoryProvider

    #
    # Generators
    #
    elcodi.core.core.generator.random_string.class: Elcodi\CoreBundle\Generator\RandomStringGenerator
    elcodi.core.core.generator.sha1.class: Elcodi\CoreBundle\Generator\Sha1Generator

    #
    # Encoders
    #
    elcodi.core.core.encoder.json.class: Elcodi\CoreBundle\Encoder\JsonEncoder
    elcodi.core.core.encoder.php.class: Elcodi\CoreBundle\Encoder\PHPEncoder
