parameters:

    #
    # Providers
    #
    elcodi.container_parameters.class: Symfony\Component\DependencyInjection\ParameterBag\ParameterBag
    elcodi.provider.manager.class: Elcodi\Component\Core\Services\ManagerProvider
    elcodi.provider.repository.class: Elcodi\Component\Core\Services\RepositoryProvider
    elcodi.mapping_provider.class: Elcodi\Component\Core\Services\MappingProvider
    elcodi.referrer_provider.class: Elcodi\Component\Core\Services\ReferrerProvider

    #
    # Generators
    #
    elcodi.generator.random_string.class: Elcodi\Component\Core\Generator\RandomGenerator
    elcodi.generator.sha1.class: Elcodi\Component\Core\Generator\Sha1Generator
    elcodi.generator.uniqid.class: Elcodi\Component\Core\Generator\UniqIdGenerator

    #
    # Encoders
    #
    elcodi.json_encoder.class: Elcodi\Component\Core\Encoder\JsonEncoder
    elcodi.php_encoder.class: Elcodi\Component\Core\Encoder\PHPEncoder

    #
    # Parser Adapter
    #
    elcodi.markdown_parser_adapter.class: Elcodi\Component\Core\Adapter\Parser\MarkdownParserAdapter
    elcodi.dummy_parser_adapter.class: Elcodi\Component\Core\Adapter\Parser\DummyParserAdapter

    #
    # EventDispatchers
    #
    elcodi.event_listener.referrer_session.class: Elcodi\Component\Core\EventListener\ReferrerSessionEventListener
