parameters:

    #
    # Entities
    #
    elcodi.core.core.entity.language.class: Elcodi\CoreBundle\Entity\Language

    #
    # Services
    #
    elcodi.core.core.service.abstract_cache_wrapper.class: Elcodi\CoreBundle\Wrapper\Abstracts\AbstractCacheWrapper
    elcodi.core.core.service.language_manager.class: Elcodi\CoreBundle\Services\LanguageManager
    elcodi.core.core.service.locale_manager.class: Elcodi\CoreBundle\Services\LocaleManager

    #
    # Providers
    #
    elcodi.core.core.service.manager_provider.class: Elcodi\CoreBundle\Services\ManagerProvider
    elcodi.core.core.service.repository_provider.class: Elcodi\CoreBundle\Services\RepositoryProvider

    #
    # Twig
    #
    elcodi.core.core.twig_extension.text_extension.class: Elcodi\CoreBundle\Twig\TextExtension
    elcodi.core.core.twig_extension.price_extension.class: Elcodi\CoreBundle\Twig\PriceExtension

    #
    # Form Types
    #
    elcodi.core.core.form_type.language.class: Elcodi\CoreBundle\Form\Type\LanguageType

    #
    # Factories
    #
    elcodi.core.core.factory.language.class: Elcodi\CoreBundle\Factory\LanguageFactory

    #
    # Generators
    #
    elcodi.core.core.generator.random_string.class: Elcodi\CoreBundle\Generator\RandomStringGenerator
    elcodi.core.core.generator.sha1.class: Elcodi\CoreBundle\Generator\Sha1Generator
