services:

    #
    # Encoders
    #
    elcodi.core.core.encoder.json:
        class: %elcodi.core.core.encoder.json.class%

    elcodi.json_encoder:
        alias: elcodi.core.core.encoder.json

    elcodi.core.core.encoder.php:
        class: %elcodi.core.core.encoder.php.class%

    elcodi.php_encoder:
        alias: elcodi.core.core.encoder.php
