services:

    #
    # Generators
    #
    elcodi.generator.random_string:
        class: %elcodi.generator.random_string.class%

    elcodi.generator.sha1:
        class: %elcodi.generator.sha1.class%
        arguments:
            - @elcodi.generator.random_string

    elcodi.generator.uniqid:
        class: %elcodi.generator.uniqid.class%
