services:

    #
    # Parser Adapter
    #
    elcodi.dummy_parser_adapter:
        class: %elcodi.dummy_parser_adapter.class%

    elcodi.markdown_parser_adapter:
        class: %elcodi.markdown_parser_adapter.class%
