services:

    #
    # Providers
    #
    elcodi.container_parameters:
        class: %elcodi.container_parameters.class%
        factory_service: service_container
        factory_method: getParameterBag

    elcodi.provider.manager:
        class: %elcodi.provider.manager.class%
        arguments:
            manager: @doctrine
            parameters_bag: @elcodi.container_parameters

    elcodi.provider.repository:
        class: %elcodi.provider.repository.class%
        arguments:
            manager_provider: @elcodi.provider.manager
            parameters_bag: @elcodi.container_parameters

    elcodi.mapping_provider:
        class: %elcodi.mapping_provider.class%
        arguments:
            mapping_implementations: %elcodi.mapping_implementations%
