services:

    #
    # Providers
    #
    elcodi.container_parameters:
        class: %elcodi.container_parameters.class%
        factory_service: service_container
        factory_method: getParameterBag

    elcodi.provider.manager:
        class: %elcodi.provider.manager.class%
        arguments:
            - @doctrine
            - @elcodi.container_parameters

    elcodi.provider.repository:
        class: %elcodi.provider.repository.class%
        arguments:
            - @elcodi.provider.manager
            - @elcodi.container_parameters

    elcodi.mapping_provider:
        class: %elcodi.mapping_provider.class%
        arguments:
            - %elcodi.mapping_implementations%

    elcodi.referrer_provider:
        class: %elcodi.referrer_provider.class%
        arguments:
            - @session
            - @request_stack
