services:

    #
    # Services
    #
    elcodi.core.core.service.abstract_cache_wrapper:
        class: %elcodi.core.core.service.abstract_cache_wrapper.class%
        abstract: true
        calls:
            - [setLanguageManager, [@elcodi.core.core.service.language_manager]]
            - [setEntityManager, [@doctrine.orm.entity_manager]]
            - [setCache, [@doctrine_cache.providers.elcodi]]
            - [setRequest, [@?request=]]
            - [setKey, []]

    elcodi.core.core.service.language_manager:
        class: %elcodi.core.core.service.language_manager.class%
        arguments:
            language_repository:  @elcodi.core.core.repository.language

    elcodi.core.core.service.locale_manager:
        class: %elcodi.core.core.service.locale_manager.class%
        arguments:
            locale: @=service("request_stack").getCurrentRequest() ? service("request_stack").getCurrentRequest().getLocale() : parameter("locale")

    #
    # Generators
    #
    elcodi.core.core.generator.random_string:
        class: %elcodi.core.core.generator.random_string.class%

    elcodi.core.core.generator.sha1:
        class: %elcodi.core.core.generator.sha1.class%
