services:

    #
    # Services
    #
    elcodi.core.core.services.abstract_cache_wrapper:
        class: %elcodi.core.core.services.abstract_cache_wrapper.class%
        abstract: true
        calls:
            - [setLanguageManager, [@elcodi.core.core.services.language_manager]]
            - [setEntityManager, [@doctrine.orm.entity_manager]]
            - [setCache, [@doctrine_cache.providers.elcodi]]
            - [setRequest, [@?request=]]
            - [setKey, []]

    elcodi.core.core.services.language_manager:
        class: %elcodi.core.core.services.language_manager.class%
        arguments:
            language_repository:  @=service("doctrine.orm.entity_manager").getRepository("ElcodiCoreBundle:Language")

    elcodi.core.core.services.locale_manager:
        class: %elcodi.core.core.services.locale_manager.class%
        arguments:
            locale: @=service("request_stack").getCurrentRequest() ? service("request_stack").getCurrentRequest().getLocale() : parameter("locale")
