services:

    elcodi.core.core.twig.text_extension:
        class: %elcodi.core.core.twig.text_extension.class%
        tags:
            - { name: twig.extension }

    elcodi.core.core.twig.price_extension:
        class: %elcodi.core.core.twig.price_extension.class%
        arguments:
            locale.info: @=service("elcodi.core.core.services.locale_manager").getLocaleInfo()
        tags:
            - { name: twig.extension }
